"""
ML inference service for sentiment prediction and issue detection.

Runs inside the main backend API using pure NumPy:
- Sentiment: 3-layer MLP forward pass + asymmetric margin thresholding.
- Issue detection: nearest-centroid lookup (only runs for negative reviews).
- Text embeddings are generated by the dedicated embedding Lambda function.
"""

import json
import os
from typing import Any
import numpy as np

from logger import get_logger

log = get_logger(__name__)

# Locate artifacts directory
# Locate artifacts directory inside backend
_BASE_DIR = os.path.dirname(os.path.abspath(__file__))
ARTIFACT_DIR = os.environ.get("ARTIFACT_DIR")
if not ARTIFACT_DIR or not os.path.exists(os.path.join(ARTIFACT_DIR, "mlp_weights.npz")):
    # 1. Check backend/src/artifacts (standard package layout)
    candidate = os.path.abspath(os.path.join(_BASE_DIR, "..", "artifacts"))
    if os.path.exists(os.path.join(candidate, "mlp_weights.npz")):
        ARTIFACT_DIR = candidate
    else:
        # 2. Check backend/artifacts (root backend layout)
        candidate = os.path.abspath(os.path.join(_BASE_DIR, "..", "..", "artifacts"))
        if os.path.exists(os.path.join(candidate, "mlp_weights.npz")):
            ARTIFACT_DIR = candidate
        else:
            ARTIFACT_DIR = os.path.abspath(os.path.join(_BASE_DIR, "..", "artifacts"))

CONFIG: dict[str, Any] = {}
mlp_weights: dict[str, np.ndarray] = {}
issue_centroids: dict[str, np.ndarray] = {}


def load_artifacts() -> None:
    """Load model weights, cluster centroids, and config into memory."""
    global CONFIG, mlp_weights, issue_centroids

    config_path = os.path.join(ARTIFACT_DIR, "config.json")
    if os.path.exists(config_path):
        with open(config_path) as f:
            CONFIG = json.load(f)
    else:
        CONFIG = {
            "sentiment": {
                "positive_margin_threshold": 0.3,
                "negative_margin_threshold": 0.0,
                "label_names": ["negative", "neutral", "positive"],
                "negative_class_id": 0,
                "neutral_class_id": 1,
                "positive_class_id": 2,
            },
            "issue_detection": {
                "cluster_names": {},
                "distance_threshold": 0.7,
                "fallback_label": "other",
            },
        }

    weights_path = os.path.join(ARTIFACT_DIR, "mlp_weights.npz")
    if os.path.exists(weights_path):
        mlp_weights = dict(np.load(weights_path))
    else:
        log.warning("mlp_weights.npz not found in %s", ARTIFACT_DIR)
        mlp_weights = {}

    centroid_path_npz = os.path.join(ARTIFACT_DIR, "issue_centroids.npz")
    centroid_path_npy = os.path.join(ARTIFACT_DIR, "issue_centroids.npy")
    if os.path.exists(centroid_path_npz):
        npz_data = np.load(centroid_path_npz)
        issue_centroids = {k: npz_data[k] for k in npz_data.files}
    elif os.path.exists(centroid_path_npy):
        issue_centroids = {"cross_category_fallback": np.load(centroid_path_npy)}
    else:
        log.warning("issue_centroids not found in %s", ARTIFACT_DIR)
        issue_centroids = {}


# Load artifacts once at startup
load_artifacts()


def relu(x: np.ndarray) -> np.ndarray:
    return np.maximum(0, x)


def mlp_forward(x: np.ndarray) -> np.ndarray:
    """
    MLP forward pass for sentiment prediction.
    Expects input shape (N, 384), returns softmax probabilities shape (N, 3).
    """
    if not mlp_weights:
        raise RuntimeError(f"MLP weights not loaded from {ARTIFACT_DIR}")

    w1, b1 = mlp_weights["net.0.weight"], mlp_weights["net.0.bias"]
    w2, b2 = mlp_weights["net.3.weight"], mlp_weights["net.3.bias"]
    w3, b3 = mlp_weights["net.6.weight"], mlp_weights["net.6.bias"]

    h1 = relu(x @ w1.T + b1)
    h2 = relu(h1 @ w2.T + b2)
    logits = h2 @ w3.T + b3

    exp_logits = np.exp(logits - logits.max(axis=1, keepdims=True))
    probs = exp_logits / exp_logits.sum(axis=1, keepdims=True)
    return probs


def apply_asymmetric_threshold(probs: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """
    Apply asymmetric thresholding to sentiment probabilities.
    Returns (final_predictions, confidence_margins).
    """
    cfg = CONFIG.get("sentiment", {})
    pos_threshold = cfg.get("positive_margin_threshold", 0.3)
    neg_threshold = cfg.get("negative_margin_threshold", 0.0)
    negative_id = cfg.get("negative_class_id", 0)
    neutral_id = cfg.get("neutral_class_id", 1)
    positive_id = cfg.get("positive_class_id", 2)

    sorted_probs = np.sort(probs, axis=1)
    margins = sorted_probs[:, -1] - sorted_probs[:, -2]
    argmax_preds = probs.argmax(axis=1)
    final_preds = argmax_preds.copy()

    positive_uncertain = (argmax_preds == positive_id) & (margins < pos_threshold)
    final_preds[positive_uncertain] = neutral_id
    negative_uncertain = (argmax_preds == negative_id) & (margins < neg_threshold)
    final_preds[negative_uncertain] = neutral_id

    return final_preds, margins


def assign_issue_cluster(embedding: np.ndarray, category: str = "") -> tuple[str, float, str]:
    """
    Nearest-centroid lookup. Only meaningful for negative-sentiment reviews.
    Returns (cluster_name, nearest_distance, cluster_source).
    """
    cfg = CONFIG.get("issue_detection", {})
    has_new_config = "per_category_clusters" in cfg

    if has_new_config and category in cfg["per_category_clusters"] and category in issue_centroids:
        centroids = issue_centroids[category]
        cluster_source = "per_category"
        cluster_names = cfg["per_category_clusters"][category]["cluster_names"]
        distance_threshold = cfg["per_category_clusters"][category].get(
            "distance_threshold", cfg.get("distance_threshold")
        )
    else:
        centroids = issue_centroids.get(
            "cross_category_fallback",
            list(issue_centroids.values())[0] if issue_centroids else np.empty((0, 384)),
        )
        cluster_source = "cross_category_fallback"
        if has_new_config:
            cluster_names = cfg.get("fallback_clusters", {}).get("cluster_names", {})
            distance_threshold = cfg.get("fallback_clusters", {}).get(
                "distance_threshold", cfg.get("distance_threshold")
            )
        else:
            cluster_names = cfg.get("cluster_names", {})
            distance_threshold = cfg.get("distance_threshold")

    if centroids.shape[0] == 0:
        return cfg.get("fallback_label", "other"), 0.0, cluster_source

    distances = np.linalg.norm(centroids - embedding, axis=1)
    nearest_idx = int(distances.argmin())
    nearest_distance = float(distances[nearest_idx])

    if distance_threshold is not None and nearest_distance > distance_threshold:
        return cfg.get("fallback_label", "other"), nearest_distance, cluster_source

    cluster_name = cluster_names.get(str(nearest_idx), cfg.get("fallback_label", "other"))
    return cluster_name, nearest_distance, cluster_source


def analyze_reviews(
    embeddings: np.ndarray,
    texts: list[str],
    categories: list[str] = None,
) -> list[dict]:
    """
    Predict sentiment and assign issue clusters for a batch of reviews.

    Input:
        embeddings: np.ndarray of shape (N, 384) from embedding Lambda
        texts: list of N review texts
        categories: list of N review category strings (optional)
    Output:
        List of dicts containing sentiment, confidence margins, probabilities,
        and issue tags (for negative reviews).
    """
    if len(texts) == 0 or embeddings.size == 0:
        return []

    probs = mlp_forward(embeddings)
    preds, margins = apply_asymmetric_threshold(probs)

    cfg = CONFIG.get("sentiment", {})
    label_names = cfg.get("label_names", ["negative", "neutral", "positive"])
    negative_id = cfg.get("negative_class_id", 0)

    results = []
    for i, text in enumerate(texts):
        sentiment_label = label_names[preds[i]]
        category = categories[i] if (categories and i < len(categories)) else ""

        issue_tag = None
        issue_distance = None
        cluster_source = None
        if preds[i] == negative_id:
            issue_tag, issue_distance, cluster_source = assign_issue_cluster(embeddings[i], category)

        results.append({
            "text": text,
            "sentiment": sentiment_label,
            "sentiment_confidence_margin": float(margins[i]),
            "sentiment_probabilities": {
                label_names[j]: float(p) for j, p in enumerate(probs[i])
            },
            "issue_tag": issue_tag,
            "issue_distance": issue_distance,
            "cluster_source": cluster_source,
        })

    return results
